markdown: kramdown
highlighter: rouge
permalink: /news/:year/:month/:day/:title/

#gauges_id: 503c5af6613f5d0f19000027
#google_analytics_id: UA-50755011-1
#google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY

repository: https://github.com/ploki/darkflow

timezone: Europe/Paris

collections:
  docs:
    output: true

name: DarkFlow • a node based image processor for astronomers
description: Get outstanding images of your astronomical captures
url: http://www.darkflow.org

logo: /img/logo-2x.png

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-mentions

exclude:
  - README.md
  - .gitignore
